version: '3.4'
services:
rasa:
  image: rasa-bot:latest
  working_dir: /app
  build: "./"
  restart: always
  
  volumes:
  - ./actions:/app/actions
  - ./data:/app/data
  - ./models:/app/models
  command: ["rasa", "run","-m models", "–enable-api", "–cors","“*””,“-p 5006"]
  ports:
  - '5006:5005'
  public: true
  networks:
  - all